Update slice-update with return code and UID check.
This change modifies slice-update to allow running smoothly from
anisble. In particular, the  background process used to trigger the
slice-update is disowned to allow a clean exit when called remotely.

This change also includes a UID check for root, since non-root users
cannot view the content of the /vsys directory.

diff --git a/slicebase/bin/slice-update b/slicebase/bin/slice-update
--- a/slicebase/bin/slice-update
+++ b/slicebase/bin/slice-update
@@ -1,9 +1,14 @@
 #!/bin/bash
 
 if [ -e /vsys/slice_update.out ] ; then
-    cat /vsys/slice_update.out &
+    cat /vsys/slice_update.out &> /dev/null & disown
     echo "1" > /vsys/slice_update.in
 else
-    echo "Error: /vsys/slice_update.out missing."
+    if [[ $EUID -ne 0 ]] ; then
+        echo "Error: please run slice-update as root."
+        exit 1
+    fi
+    echo "Error: /vsys/slice_update.out appears to be missing."
     echo "Please report this to support@measurementlab.net"
+    exit 1
 fi
